Added route for Simple Update action.
opencomputeproject/HWMgmt-DeviceMgr-DeviceManager pull request #62
Opened 2023-05-26 08:40 UTC by ehaligow

Added route for Simple Update action.

2023-05-31 13:41 UTC, MaciejMis requested changes

2023-05-31 13:41 UTC, MaciejMis commented on svc-device-manager/rest/postSimpleUpdate.go
> +		simpleUpdateRequestError := "invalid simple update request: %s" + err.Error()
Using a verb `%s` without a `Sprintf` or any other formatting method

2023-05-31 13:41 UTC, MaciejMis commented on svc-device-manager/rest/postSimpleUpdate.go
> +	ctx.Write(body)
According to the "Redfish Firmware Update White Paper" 6.1 paragraph, service can respond with `202 Accepted` which means that a task is returned in `Location` header. Please forward this task URI in header.

2023-06-13 14:15 UTC, ehaligow commented on svc-device-manager/rest/postSimpleUpdate.go
> +		simpleUpdateRequestError := "invalid simple update request: %s" + err.Error()
Done.

2023-06-13 14:21 UTC, MaciejMis approved these changes

2023-06-13 15:07 UTC, MaciejMis commented
Accepted on 13.06.2023 in community meeting.

2023-06-13 15:07 UTC, merged